/**
 * 
 */
package com.matwer.phone;

/**
 * @author Matthew
 *
 */
public class IPhone extends Phone implements Ringable {

	/**
	 * these are the member variables from Phone
	 * @param versionNumber
	 * @param batteryPercentage
	 * @param carrier
	 * @param ringTone
	 */
	public IPhone(String versionNumber, int batteryPercentage, String carrier, String ringTone) {
		// this was auto generated by STS
		super(versionNumber, batteryPercentage, carrier, ringTone);
	}

	@Override
	public String ring() {
		// ...
		return "iPone " + super.getVersionNumber() + " says " + super.getRingTone();
	}

	@Override
	public String unlock() {
		// ...
		return "Unlocking via facial recognition";
	}

	@Override
	public void displayInfo() {
		// use the getters from the Phone superclass's constructor 
		System.out.println("iPone " + super.getVersionNumber() + " from " + super.getCarrier());

	}

}
