/**
 * 
 */
package com.matwer.phone;

/**
 * @author Matthew Werner
 *
 */
public abstract class Phone {
	// declare member vairaibles
	private String versionNumber;
	private int batteryPercentage;
	private String carrier;
	private String ringTone;
	
	// create a constructor for anew phone which requires the version number, battery %, carrier & ring tone
	public Phone(String versionNumber, int batteryPercentage, String carrier, String ringTone) {
		this.versionNumber = versionNumber;
		this.batteryPercentage = batteryPercentage;
		this.carrier = carrier;
		this.ringTone = ringTone;
	}
	
	// create an abstract method that will be implemented by the subclasses
	public abstract void displayInfo();

	// auto-generated by STS
	public String getVersionNumber() {
		return versionNumber;
	}

	// auto-generated by STS
	public void setVersionNumber(String versionNumber) {
		this.versionNumber = versionNumber;
	}

	// auto-generated by STS
	public int getBatteryPercentage() {
		return batteryPercentage;
	}

	// auto-generated by STS
	public void setBatteryPercentage(int batteryPercentage) {
		this.batteryPercentage = batteryPercentage;
	}

	// auto-generated by STS
	public String getCarrier() {
		return carrier;
	}

	// auto-generated by STS
	public void setCarrier(String carrier) {
		this.carrier = carrier;
	}

	// auto-generated by STS
	public String getRingTone() {
		return ringTone;
	}
	
	// auto-generated by STS
	public void setRingTone(String ringTone) {
		this.ringTone = ringTone;
	}
}
