package com.matwer.phone;

public class PhoneTester {

	public PhoneTester() {
		// auto-generated by STS
	}

	public static void main(String[] args) {
		// create a new Galaxy phone
		Galaxy s9 = new Galaxy("S9",99,"verizon","That's powerful!");
		
		// create a new iPhone (eeewwwwww!)
		IPhone iphone10 = new IPhone("X",65,"AT&T","Rethink possible");
		
		// call the methods for the Galaxy
		s9.displayInfo();
		System.out.println(s9.ring());
		System.out.println(s9.unlock());
		
		// just adding in a little "white" space
		System.out.println();
		
		// call the methods for the iPhone
		iphone10.displayInfo();
		System.out.println(iphone10.ring());
		System.out.println(iphone10.unlock());
	}

}
